# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e2f430868adb3ac7001ac2ae03747c98"
name = "Chetai"
application_url = "https://80878465b8ae.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://80878465b8ae.ngrok-free.app/api/auth" ]

# ✅ Add App Proxy section
[app_proxy]
subpath = "chat"
prefix = "apps"
url = "https://80878465b8ae.ngrok-free.app/api/chat"
